### ISSUE TITLE
GitHub Actions Build Failing For Windows

### ISSUE THREAD

**Issue by tubbo** [linearapp/electron-forge-publisher-google-storage#7]
I'm building an Electron app with Forge, and I found this library for uploading packages to a Google Storage bucket. This seems like a great approach for starting out with Electron auto-updates, so thanks for writing it!

Both our macOS and Linux (Ubuntu) builds finish without a hitch, and I'm seeing the installers get uploaded to Google Storage. There seems to be an issue on our Windows build though. Here's the error we're getting when trying to run `electron-forge publish` within GitHub Actions:

```
An unhandled rejection has occurred inside Forge:
ResumableUploadError: A resumable upload could not be performed. The directory, C:\Users\runneradmin\.config, is not writable. You may try another upload, this time setting `options.resumable` to `false`.
    at D:\a\myproject\myproject\node_modules\@google-cloud\storage\build\src\file.js:1232:39
    at FSReqCallback.oncomplete (fs.js:156:23)
```

I tried to fork this project and set `resumable: false` in the call to `bucket.upload()`, but that didn't seem to do anything...

```diff
diff --git a/src/PublisherGoogleStorage.ts b/src/PublisherGoogleStorage.ts
index 164e5d1..b2fff53 100644
--- a/src/PublisherGoogleStorage.ts
+++ b/src/PublisherGoogleStorage.ts
@@ -73,6 +73,7 @@ export default class PublisherGoogleStorage {
         await bucket.upload(artifact.path, {
           gzip: true,
           destination,
+          resumable: false,
           metadata: {
             "cache-control": "public, max-age=31536000" // 1 year
           },
```

Not sure where to turn from here. Has anyone else had this issue?

**Comment by tubbo** [comment]
forked and released our own version https://github.com/nerdstgamers/electron-forge-publisher-google-storage
